//home.style.ts
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8FAFC' },
  scrollView: { flex: 1 },
  container: { flexGrow: 1, paddingHorizontal: 24, paddingVertical: 32, gap: 28 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerText: { gap: 4 },
  logoText: { fontSize: 28, fontWeight: '800', color: '#0F172A', letterSpacing: 1 },
  subtitle: { fontSize: 14, color: '#64748B' },
  profileButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInitial: { fontSize: 16, fontWeight: '700', color: '#2563EB' },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  section: { gap: 16 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#2563EB',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  addButtonText: { fontSize: 13, fontWeight: '700', color: '#FFFFFF' },
  searchInput: {
    height: 48,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    fontSize: 14,
    color: '#0F172A',
  },
  filterRow: { flexDirection: 'row', gap: 8 },
  listLoading: { paddingVertical: 40 },
  assetsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  emptyState: { alignItems: 'center', paddingVertical: 40, gap: 6 },
  emptyTitle: { fontSize: 15, fontWeight: '700', color: '#0F172A' },
  emptyText: { fontSize: 13, color: '#64748B', textAlign: 'center' },
});