import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F8FAFC" },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "#F8FAFC",
  },
  loadingText: { color: "#64748B", fontSize: 14 },
  layout: { flex: 1, flexDirection: "row" },
  sidebar: { width: 250, backgroundColor: "#0F172A", padding: 20, gap: 8 },
  brand: {
    color: "#FFFFFF",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 1,
  },
  brandSub: { color: "#94A3B8", fontSize: 12, marginBottom: 18 },
  navButton: {
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 2,
  },
  navButtonActive: { backgroundColor: "#1E40AF" },
  navText: { color: "#CBD5E1", fontSize: 14, fontWeight: "600" },
  navTextActive: { color: "#FFFFFF" },
  sidebarBottom: { marginTop: "auto", gap: 10 },
  userMini: { borderTopWidth: 1, borderTopColor: "#334155", paddingTop: 14 },
  userName: { color: "#FFFFFF", fontWeight: "700", fontSize: 13 },
  userRole: { color: "#94A3B8", fontSize: 11, marginTop: 3 },
  logoutButton: {
    borderWidth: 1,
    borderColor: "#475569",
    borderRadius: 9,
    padding: 10,
    alignItems: "center",
  },
  logoutText: { color: "#E2E8F0", fontWeight: "700", fontSize: 12 },
  content: { flex: 1 },
  scroll: { flex: 1 },
  container: {
    maxWidth: 1220,
    width: "100%",
    alignSelf: "center",
    padding: 28,
    gap: 18,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  title: { color: "#0F172A", fontSize: 28, fontWeight: "800" },
  subtitle: { color: "#64748B", fontSize: 14, marginTop: 5, lineHeight: 20 },
  headerActions: { flexDirection: "row", gap: 8 },
  button: {
    minHeight: 40,
    paddingHorizontal: 15,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPrimary: { backgroundColor: "#2563EB" },
  buttonSecondary: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  buttonDanger: {
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  buttonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 13 },
  buttonTextDark: { color: "#334155", fontWeight: "700", fontSize: 13 },
  buttonTextDanger: { color: "#B91C1C", fontWeight: "700", fontSize: 13 },
  error: {
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: 10,
    padding: 14,
  },
  errorTitle: { color: "#991B1B", fontWeight: "800", fontSize: 13 },
  errorText: { color: "#B91C1C", fontSize: 13, marginTop: 4 },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  metric: {
    flexGrow: 1,
    flexBasis: 180,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    padding: 16,
  },
  metricLabel: { color: "#64748B", fontSize: 12, fontWeight: "600" },
  metricValue: {
    color: "#0F172A",
    fontSize: 27,
    fontWeight: "800",
    marginTop: 5,
  },
  metricHint: { color: "#94A3B8", fontSize: 11, marginTop: 3 },
  panel: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    overflow: "hidden",
  },
  toolbar: {
    padding: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  search: {
    flex: 1,
    minWidth: 220,
    height: 40,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 9,
    paddingHorizontal: 12,
    color: "#0F172A",
    backgroundColor: "#FFFFFF",
  },
  filter: {
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
  },
  filterActive: { backgroundColor: "#DBEAFE" },
  filterText: { color: "#475569", fontSize: 12, fontWeight: "700" },
  row: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  rowMain: { flex: 1, minWidth: 0 },
  rowTitle: { color: "#0F172A", fontSize: 14, fontWeight: "700" },
  rowSub: { color: "#64748B", fontSize: 12, marginTop: 3 },
  rowMeta: { color: "#94A3B8", fontSize: 11, marginTop: 3 },
  actions: {
    flexDirection: "row",
    gap: 7,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  badge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#F1F5F9",
  },
  badgeText: { color: "#475569", fontSize: 10, fontWeight: "800" },
  badgeGreen: { backgroundColor: "#DCFCE7" },
  badgeGreenText: { color: "#166534" },
  badgeRed: { backgroundColor: "#FEE2E2" },
  badgeRedText: { color: "#991B1B" },
  badgeBlue: { backgroundColor: "#DBEAFE" },
  badgeBlueText: { color: "#1D4ED8" },
  empty: { padding: 30, alignItems: "center" },
  emptyText: { color: "#94A3B8", fontSize: 13 },
  sectionTitle: { color: "#0F172A", fontSize: 17, fontWeight: "800" },
  sectionHint: { color: "#94A3B8", fontSize: 12 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  auditRow: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    flexDirection: "row",
    gap: 10,
  },
  auditAction: { color: "#0F172A", fontWeight: "700", fontSize: 13 },
  auditDetail: { color: "#64748B", fontSize: 11, marginTop: 3 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.45)",
    justifyContent: "center",
    padding: 18,
  },
  modal: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "90%",
    alignSelf: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    overflow: "hidden",
  },
  modalHeader: {
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: { color: "#0F172A", fontSize: 18, fontWeight: "800" },
  close: {
    color: "#64748B",
    fontSize: 20,
    fontWeight: "700",
    paddingHorizontal: 5,
  },
  modalBody: { padding: 18 },
  field: { marginBottom: 13 },
  label: { color: "#334155", fontSize: 12, fontWeight: "700", marginBottom: 6 },
  input: {
    height: 42,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 9,
    paddingHorizontal: 12,
    color: "#0F172A",
    backgroundColor: "#FFFFFF",
  },
  inputMultiline: {
    minHeight: 85,
    height: 85,
    paddingTop: 10,
    textAlignVertical: "top",
  },
  selectRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  select: {
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  selectActive: { backgroundColor: "#DBEAFE", borderColor: "#93C5FD" },
  selectText: { color: "#475569", fontSize: 12, fontWeight: "600" },
  selectTextActive: { color: "#1D4ED8" },
  modalFooter: {
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  permissionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  permission: {
    width: "48%",
    minWidth: 210,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 9,
    padding: 10,
    backgroundColor: "#F8FAFC",
  },
  permissionActive: { borderColor: "#93C5FD", backgroundColor: "#EFF6FF" },
  permissionText: { color: "#475569", fontSize: 11, fontWeight: "600" },
  permissionTextActive: { color: "#1D4ED8" },
  mobileSidebar: { display: "none" },
});
